# Find mel min/max

In [3]:
from conf.hydra_config import (
    TrainingUnitEncoderConfig_STEP1,
)
import logging
import torch


cfg = TrainingUnitEncoderConfig_STEP1
device = torch.device("cuda" if torch.cuda.is_available() and cfg.train.on_GPU else "cpu")

logger = logging.getLogger()
logger.setLevel(logging.DEBUG)

In [4]:
cfg.dataset.name

'LibriTTS'

In [5]:
mel_min = torch.load(cfg.dataset.mel_min_path).to(device)
mel_min.shape, mel_min

(torch.Size([80]),
 tensor([-11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129], device='cuda:0'))

In [6]:
original_mel_min = torch.load("unitspeech/checkpoints/mel_min.pt")
original_mel_min.shape, original_mel_min

(torch.Size([80]),
 tensor([-11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129, -11.5129,
         -11.5129, -11.5129, -11.5129]))

In [7]:
for i, (v1, v2) in enumerate(zip(mel_min.flatten(), original_mel_min.flatten())):
    if v1 == v2:
        continue
        print(f"[EQUAL]At index {i}, mel_min is {v1} while original_mel_min is {v2}")
    if v1 != v2:
        print(f"[NOT EQUAL]At index {i}, mel_min is {v1} while original_mel_min is {v2}")

In [8]:
mel_max = torch.load(cfg.dataset.mel_max_path).to(device)
mel_max.shape, mel_max

(torch.Size([80]),
 tensor([ 2.2396,  1.7412,  2.0047,  1.8635,  1.6160,  1.6770,  1.7164,  1.6729,
          1.9186,  1.9919,  1.9429,  2.0060,  2.0480,  2.1126,  2.1814,  2.0440,
          1.9951,  1.9164,  2.1956,  1.9244,  1.9685,  1.8858,  1.6691,  1.6388,
          2.1799,  1.7118,  1.5506,  1.5032,  1.6166,  1.7240,  1.9226,  1.9259,
          1.6882,  1.5648,  1.2986,  1.4236,  1.3465,  1.0905,  1.0518,  1.1202,
          1.1056,  0.9698,  0.9007,  0.9808,  0.9551,  0.9867,  0.7309,  0.8902,
          0.5384,  0.7088,  0.5863,  0.4398,  0.3234,  0.4925,  0.6535,  0.4604,
          0.3580,  0.6003,  0.7013,  0.7245,  0.7301,  0.7176,  0.4676,  1.1647,
          0.9116,  0.5581,  0.5944,  0.0812,  0.6586,  0.3508,  0.1807,  0.2859,
          0.5973,  0.0491, -0.0368, -0.0094,  0.1095, -0.0434,  0.0059,  0.1408],
        device='cuda:0'))

In [9]:
original_mel_max = torch.load("unitspeech/checkpoints/mel_max.pt")
original_mel_max.shape, original_mel_max

(torch.Size([80]),
 tensor([2.3678, 1.9858, 2.0981, 2.0714, 1.9077, 2.2800, 2.3345, 2.3407, 2.1605,
         2.2150, 2.2823, 2.1748, 2.1844, 2.3054, 2.3514, 2.2928, 2.1999, 2.2282,
         2.2321, 2.0936, 2.1599, 2.1016, 2.1892, 2.0314, 2.1798, 2.2661, 2.0354,
         2.1316, 2.1162, 1.9804, 1.9803, 1.9256, 1.7991, 1.8490, 2.0034, 1.6449,
         1.5683, 1.7728, 1.6321, 1.5499, 1.6727, 1.5721, 1.3449, 1.4617, 1.3555,
         1.4562, 1.1820, 1.0871, 1.1762, 0.9916, 0.9349, 0.9958, 1.1382, 1.0810,
         1.1063, 0.9895, 0.9962, 1.4600, 1.4202, 1.1430, 1.3783, 0.9589, 0.9599,
         1.1538, 0.9055, 0.6158, 0.8025, 0.7124, 0.6566, 0.8171, 0.8327, 0.7887,
         0.8496, 0.6723, 0.6793, 0.5739, 0.9136, 0.8758, 0.8724, 0.6244]))

In [12]:
for i, (v1, v2) in enumerate(zip(mel_max.flatten(), original_mel_max.flatten())):
    if v1 == v2:
        print(f"[EQUAL]At index {i}, mel_max is {v1} while original_mel_max is {v2}")
    if v1 != v2:
        print(f"[NOT EQUAL]At index {i}, mel_max is {v1} while original_mel_max is {v2}")

Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue
Continue


# Dataset

In [ ]:
from data import TextMelSpeakerDataset


train_dataset = TextMelSpeakerDataset(filelist_path=cfg.dataset.train_filelist_path,
                                        random_seed=cfg.train.seed,
                                        add_blank=cfg.data.add_blank,
                                        n_fft=cfg.data.n_fft,
                                        n_mels=cfg.data.n_feats,
                                        sample_rate=cfg.data.sampling_rate,
                                        hop_length=cfg.data.hop_length,
                                        win_length=cfg.data.win_length,
                                        f_min=cfg.data.mel_fmin,
                                        f_max=cfg.data.mel_fmax)

# Embeddings

In [9]:
import torch

tensor = torch.arange(10).unsqueeze(1).repeat(1, 256)
# tensor = torch.full((10, 256), 10)

In [10]:
tensor.shape

torch.Size([10, 256])

In [12]:
tensor[2]

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [33]:
weigths = torch.arange(257).float().unsqueeze(1).repeat(1, 256)
weigths.shape

torch.Size([257, 256])

In [25]:
from torch import nn
embeddings = nn.Embedding.from_pretrained(weigths, freeze=True)

In [32]:
idx = torch.LongTensor([2, 3])
embeddings(idx)

tensor([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2.,

In [40]:
weigths = torch.randn(257, 256)

In [56]:
import os


def load_speaker_embs(embs_path: str, normalize=True):
    """Load speaker embeddings from .pt files in a directory.

    Args:
        embs_path (str): Folder with .pt files containing speaker embeddings for the current dataset

    Returns:
        torch.Tensor: Tensor containing all speaker embeddings
    """
    embs = []
    for spkr_id in sorted(os.listdir(embs_path)):
        if spkr_id.endswith('.pt'):
            spkr_emb = torch.load(os.path.join(embs_path, spkr_id))

            if normalize:
                spkr_emb = spkr_emb / spkr_emb.norm()
            embs.append(spkr_emb)
        else:
            raise ValueError(f"Speaker embedding file {spkr_id} is not a .pt file.")
    return torch.stack(embs)

In [57]:
test_embs = load_speaker_embs(os.path.join("unitspeech/checkpoints/embs/", "LJSpeech"))

In [58]:
speaker_embeddings = torch.nn.Embedding.from_pretrained(test_embs).to("cuda")

In [59]:
speaker_embeddings(torch.LongTensor([0]).to("cuda"))

tensor(1.0000, device='cuda:0')